name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}  # Dùng TOKEN mới

    - name: Build & Push Vote Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/voting-app:vote-${{ github.sha }} ./vote
        docker push ${{ secrets.DOCKER_USERNAME }}/voting-app:vote-${{ github.sha }}

    - name: Build & Push Result Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/voting-app:result-${{ github.sha }} ./result
        docker push ${{ secrets.DOCKER_USERNAME }}/voting-app:result-${{ github.sha }}

    - name: Build & Push Worker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/voting-app:worker-${{ github.sha }} ./worker
        docker push ${{ secrets.DOCKER_USERNAME }}/voting-app:worker-${{ github.sha }}
